
* c. 80
  Вычислить квадратного корня...
  Вычислить квадраный корень...
* c. 83
  ...мы упомянули, что это лишь частный случайНьютона метод||Newthon's method|||метода Ньютона
* c. 96
  Упражнение 2.1
  Определите улучшенную версию mul-rat
  должно быть
  Определите улучшенную версию make-rat
* с. 241
  в нескольких местах setcar! вместо set-car!
* с. 245
  рис. 3.17 не отличается от 3.16, а должен
* с. 250
  Очередь, таким образом, представляется в виде пары указателей frontptr 
  вместо front-ptr
* с. 253
  упр. 3.23
  ... frontinsertdeque! вместо front-insert-deque!
* с. 266
  которая работает с theagenda
  должно быть:
  которая работает с the-agenda
* с. 306
  Такая запись имеет смысл, потому что описывает sequence ...
  должно быть
  Такая запись имеет смысл, потому что описывает integers ...
* с. 311
  элементы (scale-streams 2) также принадлежат S
  должно быть
  элементы (scale-stream S 2) также принадлежат S
* с. 312
  (define cosine-stream ...
  должно быть
  (define cosine-series ...
* с. 348
  Хьюго Дум хочет переупорядочить ветви cond так, чтобы...
  должно быть
  Хьюго Дум хочет переупорядочить ветви eval так, чтобы...
* c. 396
  Процедура верхнего уровня ambeval (сходная с версией eval?, приведённой в разделе 4.1.7)
  должно быть
  Процедура верхнего уровня ambeval (сходная с версией eval, приведённой в разделе 4.1.7)
* c. 413
  (rule (живет-около ?person-1 ?person-2)
        (and (адрес ?person-1 (?town . ?rest-1))
             (адрес ?person-1 (?town . ?rest-2))
             (not (same ?person-1 ?person-2))))
  должно быть
  (rule (живет-около ?person-1 ?person-2)
      (and (адрес ?person-1 (?town . ?rest-1))
           (адрес ?person-2 (?town . ?rest-2))
           (not (same ?person-1 ?person-2))))
* с. 422
  начало страницы:
  быть ?b
  должно быть:
  быть b

* с. 430
  Эти преобразования производятся процедурами query-syntax-process и contract-questionmark
  должно быть
  Эти преобразования производятся процедурами query-syntax-process и contract-question-mark
* с. 434
  либо, если сопоставление неудачнно, the-emptystream
  должно быть
  либо, если сопоставление неудачнно, the-empty-stream
