
* c. 80
  Вычислить квадратного корня...
  Вычислить квадраный корень...
* c. 83
  ...мы упомянули, что это лишь частный случайНьютона метод||Newthon's method|||метода Ньютона
* c. 96
  Упражнение 2.1
  Определите улучшенную версию mul-rat
  должно быть
  Определите улучшенную версию make-rat
* с. 241
  в нескольких местах setcar! вместо set-car!
* с. 245
  рис. 3.17 не отличается от 3.16, а должен
* с. 250
  Очередь, таким образом, представляется в виде пары указателей frontptr 
  вместо front-ptr
* с. 253
  упр. 3.23
  ... frontinsertdeque! вместо front-insert-deque!
* с. 266
  которая работает с theagenda
  должно быть:
  которая работает с the-agenda
* с. 306
  Такая запись имеет смысл, потому что описывает sequence ...
  должно быть
  Такая запись имеет смысл, потому что описывает integers ...
* с. 311
  элементы (scale-streams 2) также принадлежат S
  должно быть
  элементы (scale-stream S 2) также принадлежат S
* с. 312
  (define cosine-stream ...
  должно быть
  (define cosine-series ...
* с. 348
  Хьюго Дум хочет переупорядочить ветви cond так, чтобы...
  должно быть
  Хьюго Дум хочет переупорядочить ветви eval так, чтобы...
