(define (extract-labels text receive)
  (if (null? text)
      (receive '() '())
      (extract-labels (cdr text)
                      (lambda (insts labels)
                        (let ((next-inst (car text)))
                          (if (symbol? next-inst)
                              (let ((existing (assoc next-inst labels)))
                                (if (null? existing)
                                    (receive insts (cons (make-label-entry next-inst insts) labels))
                                    (error "Dublicate label" next-inst)))
                              (receive (cons (make-instruction next-inst) insts) labels)))))))